CREATE TABLE user
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 식별자',
    username VARCHAR(255) NOT NULL COMMENT '유저명',
    email VARCHAR(255) NOT NULL COMMENT '이메일',
    password VARCHAR(255) NOT NULL COMMENT '비밀번호',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);

CREATE TABLE schedule
(
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '고유 식별자',
    title VARCHAR(255) NOT NULL COMMENT '제목',
    contents VARCHAR(255) NOT NULL COMMENT '내용',
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '작성일',
    updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정일'
);